name: 03 - Workflow Runners
on:
  push:
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job is running on the ubuntu runner"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: echo "This job is running on a Windows runner"
  
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: This job is running on WacOS runner"

